### ISSUE TITLE
dlog script fail, missing classes

### ISSUE THREAD

**Issue by hanxue** [twitter/distributedlog#33]
I am using the 0.3.51-RC0 `dlog` script on Mac OS X 10.10.5 as well as Debian Jessie. `dlog local` produces this error

```
$ distributedlog-service/bin/dlog local 7
070
JMX enabled by default
cat: /home/vagrant/distributed-log/distributedlog-service/target/cached_classpath.txt: No such file or directory
Error: Could not find or load main class com.twitter.distributedlog.LocalDLMEmulator
```

`dlog admin` fails with this error

```
$ distributedlog-service/bin/dlog admin
JMX enabled by default
cat: /home/vagrant/distributed-log/distributedlog-service/target/cached_classpath.txt: No such file or directory
Error: Could not find or load main class com.twitter.distributedlog.tools.Too
```

**Comment by sijie** [comment]
@hanxue interesting. I tried on my MAC "10.10.5" seems to be fine. what is your bash version?

in the script, it checks if the lib directory exists. if the lib directory exists, it would use the lib to build the classpath; otherwise it would use the maven build result. from the output you pasted, it seems that your bash failed to find the "$DLOG_HOME/lib". If you could share your bash version, I could try to debug. Or could you try to add "echo $DLOG_HOME" in the dlog script to see what is $DLOG_HOME?

```
if [ -d "$DLOG_HOME/lib" ]; then
    for i in $DLOG_HOME/lib/*.jar; do
        DLOG_CLASSPATH=$DLOG_CLASSPATH:$i
    done
else
    add_maven_deps_to_classpath
fi
```

**Comment by franckcuny** [comment]
@hanxue alternatively, could you run the script with `bash -x distributedlog-service/bin/dlog local 7` ? And copy the output to this issue.

**Comment by sijie** [comment]
@hanxue any updates?

**Comment by sijie** [comment]
closed the issue here. as we moved the issue tracking to https://issues.apache.org/jira/browse/DL
