### ISSUE TITLE
Namespace in global replacation setup

### ISSUE THREAD

**Issue by sunmoonone** [twitter/distributedlog#41]
Hi, I successfully setup three distributedlog clusters across regions according to this [global replicated log](http://distributedlog.io/globalreplicatedlog/main.html) doc.  In order to replicate segments to different ensembles, should write proxies in different regions bind to the same namespace or should they bind to different namespaces?

**Comment by sijie** [comment]
@sunmoonone 

we moved distributedlog to apache incubator. 

Can you send an email to dev@distributedlog.incubator.apache.org? We will help you from there. That would also benefit other people that subscribed to dev@distributedlog.incubator.apache.org . Does that work for you? If not, we can work here too.

**Comment by sunmoonone** [comment]
@sijie OK

**Comment by sijie** [comment]
@sunmoonone 

in short answer, all the write proxies have to use same namespace.

In a longer answer, in order to setup a global cluster, you have to setup a global zookeeper cluster, not 3 separated zk clusters.

Let's say, you have 3 DCs - A, B and C. You have 3 zk nodes each DC. You need to put all 9 zk nodes into same ensemble, so they form as a global zk cluster.

So the bookies on each DC will use the global zk for metadata store and they will available globally.

You will have to create one single namespace. All the write proxies on each DC use the same namespace. After this setup, you clients from anywhere are able to use the global replicated log. 

Does that make sense?

(Out of curiosity, why did you reopen this issue here? You cannot access the Apache incubator?)

**Comment by sunmoonone** [comment]
@sijie thanks a lot

I'm confused about the `-l option` for namespace

yes, 
* my zk ensemble is the same as what you explained, they communicates through wan ip
* my bookie ensembles have different `zkLedgersRootPath`  in order to separate with other ensembles
```
#region 1:
zkLedgersRootPath=/messaging/bookkeeper-region1/ledgers

#region 2:
zkLedgersRootPath=/messaging/bookkeeper-region2/ledgers

#region 3:
zkLedgersRootPath=/messaging/bookkeeper-region3/ledgers
```
* And all the bookie and writeproxy nodes bind to a wan ip, because I think writeproxies may need to talk to bookies in other regions using the `RegionAwareEnsemblePlacementPolicy`
* Hostname of all nodes follow this format `region-rac-xxx-id`

Should I set the value for `-l` with multiple bookkeeper ledgers path like this?

```
-l /messaging/bookkeeper-region1/ledgers,/messaging/bookkeeper-region2/ledgers
,/messaging/bookkeeper-region3/ledgers
```

Or should I make all the bookie nodes use the same `zkLedgersRootPath` to form one single bookie-ensemble?

 (I have sent a mail to  dev@distributedlog.incubator.apache.org, but there was no reply so I reopened this issues here :D )

**Comment by sunmoonone** [comment]
I tried to give multiple paths to `-l` when binding namespace and failed

**Comment by sijie** [comment]
@sunmoonone Ah I see.

for a global setup, you need to make sure all the bookies announced to the same 'zkLedgersRootPath' to form a unique global ensemble.

for the mail to dev, it seems to be a problem of apache mail list. I think people only can send email when he/she is subscribed to mail list (subscribe via dev-subscribe@d.i.a.o), otherwise the moderator has to approved the email. I just approved a few minutes before this comment.
